version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn weather_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: weather_db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: